name:                selang
version:             0.1.0.0
github:              "Technius/selang"
license:             MIT
author:              "Bryan Tan"
maintainer:          "techniux@gmail.com"
copyright:           "2018 Bryan Tan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Technius/selang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- mtl
- containers
- recursion-schemes
- deriving-compat
- prettyprinter

library:
  source-dirs: src

executables:
  selang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - selang

tests:
  selang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - selang
